version: '2'
volumes:
  nexus-registry:
    driver_opts:
      share: "{CIFS_SHARE}
    driver: cifs
services:
  nexus:
    image: sonatype/nexus3:3.12.0
    volumes:
    - nexus-registry:/nexus-data
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: nexus=true
      traefik.acme: 'true'
      traefik.enable: 'true'
      traefik.docker.port: "${DOCKER_PORT}"
      traefik.docker.backend: "${DOCKER_BACKEND}"
      traefik.docker.frontend.rule: "Host:${DOCKER_BACKEND}.${NEXUS-DOMAIN}"
      traefik.nexus.port: "${NEXUS_PORT}"
      traefik.nexus.backend: "${NEXUS_BACKEND}"
      traefik.nexus.frontend.rule: "Host:${NEXUS_BACKEND}.${NEXUS-DOMAIN}"
      traefik.nexus-internal.port: "${NEXUS-INTERNAL_PORT}"
      traefik.nexus-internal.frontend.rule: "Host:${NEXUS-INTERNAL_BACKEND}.${NEXUS-DOMAIN}"
      traefik.nexus-internal.backend: ${NEXUS-INTERNAL_BACKEND}